### ISSUE TITLE
[WEBUI]Can't start web ui

### ISSUE THREAD

**Issue by AngersZhuuuu** [alibaba/SparkCube#2]
When I run this, I meet a issue about WEB UI, and I have check the code seems  ok, any point I have missed?
```
java.lang.Exception: Could not find resource path for Web UI: com/alibaba/sparkcube/execution/ui/static
	at org.apache.spark.ui.JettyUtils$.createStaticHandler(JettyUtils.scala:197)
	at org.apache.spark.ui.WebUI.addStaticHandler(WebUI.scala:121)
	at org.apache.spark.ui.SparkCubeTab.<init>(SparkCubeTab.scala:42)
	at org.apache.spark.sql.CubeSharedState$$anonfun$3.apply(CubeSharedState.scala:47)
	at org.apache.spark.sql.CubeSharedState$$anonfun$3.apply(CubeSharedState.scala:47)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.sql.CubeSharedState.<init>(CubeSharedState.scala:47)
	at org.apache.spark.sql.CubeSharedState$.get(CubeSharedState.scala:63)
	at com.alibaba.sparkcube.CubeManager.cubeCatalog(CubeManager.scala:213)
	at com.alibaba.sparkcube.CubeManager.listAllCaches(CubeManager.scala:230)
	at org.apache.spark.ui.SparkCubePage.render(SparkCubePage.scala:54)
	at org.apache.spark.ui.WebUI$$anonfun$2.apply(WebUI.scala:84)
	at org.apache.spark.ui.WebUI$$anonfun$2.apply(WebUI.scala:84)
	at org.apache.spark.ui.JettyUtils$$anon$3.doGet(JettyUtils.scala:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.spark_project.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.spark_project.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.spark_project.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.spark_project.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.spark_project.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.spark_project.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.spark_project.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.spark_project.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.spark_project.jetty.server.Server.handle(Server.java:539)
	at org.spark_project.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.spark_project.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.spark_project.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.spark_project.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.spark_project.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.spark_project.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
```

**Comment by AngersZhuuuu** [comment]
cc @adrian-wang

**Comment by adrian-wang** [comment]
@AngersZhuuuu How did you setup the jar in your classpath?

**Comment by AngersZhuuuu** [comment]
> @AngersZhuuuu How did you setup the jar in your classpath?

Build with our spark version and startup with --jar ~/xx/xx/sparkcube-0.3.jar

**Comment by AngersZhuuuu** [comment]
should use spark.driver.extraClassPath.

**Comment by adrian-wang** [comment]
> should use spark.driver.extraClassPath.

I think that should resolve the issue, right ?
